// Code generated by MockGen. DO NOT EDIT.
// Source: service/list.go

// Package mock is a generated GoMock package.
package mock

import (
	dtos "linked-page/dtos"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockListServiceInterface is a mock of ListServiceInterface interface.
type MockListServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockListServiceInterfaceMockRecorder
}

// MockListServiceInterfaceMockRecorder is the mock recorder for MockListServiceInterface.
type MockListServiceInterfaceMockRecorder struct {
	mock *MockListServiceInterface
}

// NewMockListServiceInterface creates a new mock instance.
func NewMockListServiceInterface(ctrl *gomock.Controller) *MockListServiceInterface {
	mock := &MockListServiceInterface{ctrl: ctrl}
	mock.recorder = &MockListServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockListServiceInterface) EXPECT() *MockListServiceInterfaceMockRecorder {
	return m.recorder
}

// InsertList mocks base method.
func (m *MockListServiceInterface) InsertList(insertList *dtos.InsertListRequest) (uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertList", insertList)
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertList indicates an expected call of InsertList.
func (mr *MockListServiceInterfaceMockRecorder) InsertList(insertList interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertList", reflect.TypeOf((*MockListServiceInterface)(nil).InsertList), insertList)
}

// SetListByListId mocks base method.
func (m *MockListServiceInterface) SetListByListId(patchList *dtos.PatchListRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetListByListId", patchList)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetListByListId indicates an expected call of SetListByListId.
func (mr *MockListServiceInterfaceMockRecorder) SetListByListId(patchList interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetListByListId", reflect.TypeOf((*MockListServiceInterface)(nil).SetListByListId), patchList)
}
